services:
  django:
    container_name: spokanepython-django
    image: ghcr.io/spokanetech/spokanepythonweb:latest
    pull_policy: always
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    env_file:
      - .env
    command: "./entrypoint.sh"
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spokanepython.rule=Host(`spokanepython.com`) || Host(`www.spokanepython.com`)"
      - "traefik.http.services.spokanepython.loadbalancer.server.port=8000"

    networks:
      - default
      - proxy
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: spokanepython-postgres
    volumes:
      - spokanepython_postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
  proxy:
    name: proxy

volumes:
  spokanepython_postgres:
