services:
  django:
    container_name: dbslusser-django
    image: ghcr.io/davidslusser/web:latest
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    env_file:
      - .env
    command: "./entrypoint.sh"
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbslusser.rule=Host(`dbslusser.space`) || Host(`www.dbslusser.space`)"
      - "traefik.http.routers.dbslusser.entrypoints=websecure"
      - "traefik.http.routers.dbslusser.tls.certresolver=myresolver"
      - "traefik.http.services.dbslusser.loadbalancer.server.port=8000"

    networks:
      - default
      - web
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: dbslusser-postgres
    volumes:
      - dbslusser_postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"      
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
  web:
    external: true

volumes:
  dbslusser_postgres:
