services:
  django:
    container_name: dbslusser-web-django
    image: ghcr.io/davidslusser/web:latest
    pull_policy: always
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    env_file:
      - .env
    command: "./entrypoint.sh"
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbslusser-web.rule=Host(`dbslusser.com`) || Host(`www.dbslusser.com`)"
      - "traefik.http.services.dbslusser-web.loadbalancer.server.port=8000"

    networks:
      - default
      - proxy
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: dbslusser-web-postgres
    volumes:
      - dbslusser_postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"      
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
  proxy:
    name: proxy

volumes:
  dbslusser_postgres:
