services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: "${WATCHTOWER_POLL_INTERVAL:-300}"
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable
    networks:
      - proxy

networks:
  proxy:
    external: true
